name: test_action
on: [push]
permissions:
  actions: read # for detecting the Github Actions environment.
  contents: read
  id-token: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: look into filesystem
        run: |
         echo "Hi"
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Install jfrog cli
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.ARTIFACTORY_URL }}
        with:
         oidc-provider-name: jfrog-github-oidc
         
      - name: gh-action-checkout
        id: checkout
        uses: carmithersh/gh-action-checkout@main      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:           
          rt-url: ${{ vars.ARTIFACTORY_URL }}
          rt-repo: 'gh-remote'
          rt-token: ${{ steps.setup-cli.outputs.oidc-token }}
          gh-token: ${{ secrets.GHPAT }} # required in case an action resides on a private repo
          fail-on-error: true
      
      - name: look into filesystem
        run: |
         pwd
         echo "./jfrog-proxy/"
         ls -ltr -R ./jfrog-proxy/         
         echo "/home/runner/work/_actions:"
         ls -ltr -R /home/runner/work/_actions
         
      # This action will be downloaded only by the JFrog gh-action-checkout          
      - name: Hello world action step
        id: hello
        uses: ./jfrog-proxy/carmithersh/test_action@3df21c32bade19faf0f04741abe125e3e3b25ef7
        with:
          who-to-greet: 'Carmit'

       # This action will be downloaded by Github on job setup and overridden by the JFrog gh-action-checkout
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
         version: latest  

      # Testing the opa action    
      - name: check if opa exists
        id: check_opa
        run: |
          opa -h   
          
      # Testing the local test_action action
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
         
