name: test_action
on: [push]
permissions:
  actions: read # for detecting the Github Actions environment.
  contents: read
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: gh-action-checkout
        id: checkout
        uses: carmithersh/gh-action-checkout@main        
        with: 
          repo: 'carmithersh/test_action@3df21c32bade19faf0f04741abe125e3e3b25ef7'
          gh-token: ${{ secrets.GHPAT }}
          rt-url: 'https://eldada.jfrog.io'
          rt-repo: 'gh-remote'
          rt-token: '4444'
          destination-dir: '/home/runner/work/_actions'
          
      - name: look into filesystem
        run: |
         echo "/home/runner/work/_actions/carmithersh/test_action"
         ls -ltr /home/runner/work/_actions/carmithersh/test_action
         echo "/home/runner/work/"
         ls -ltr /home/runner/work/
         echo "/home/runner/work/_actions:"
         ls -ltr /home/runner/work/_actions
         echo "/home/runner/work/_actions/carmithersh:"
         ls -ltr /home/runner/work/_actions/carmithersh
         echo "/home/runner/work/_actions"
         ls -ltr -R /home/runner/work/_actions
         
      - name: Hello world action step
        id: hello
        uses: carmithersh/test_action@3df21c32bade19faf0f04741abe125e3e3b25ef7
        with:
          who-to-greet: 'Carmit'
          token: ${{ secrets.MYPAT }}
          
      - name: look into filesystem
        run: |      
         echo "/home/runner/work/_actions"
         ls -ltr -R /home/runner/work/_actions
         
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
         
