name: test_action
on: [push]
permissions:
  actions: read # for detecting the Github Actions environment.
  contents: read
  id-token: write
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: env
        run: |
         echo "print all env"
         env
         
      - name: gh-action-checkout
        id: checkout
        uses: carmithersh/gh-action-checkout@main      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:           
          rt-url: 'https://eldada.jfrog.io'
          rt-repo: 'gh-remote'
          rt-token: '4444'
      
      - name: look into filesystem
        run: |
         echo "/home/runner/work/_actions/carmithersh/test_action"
         ls -ltr /home/runner/work/_actions/carmithersh/test_action
         echo "/home/runner/work/"
         ls -ltr /home/runner/work/
         echo "/home/runner/work/_actions:"
         ls -ltr -R /home/runner/work/_actions
         
                 
      - name: Hello world action step
        id: hello
        uses: carmithersh/test_action@3df21c32bade19faf0f04741abe125e3e3b25ef7
        with:
          who-to-greet: 'Carmit'
          
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
         version: latest  
      - name: check if opa exists
        id: check_opa
        run: |
          opa -h   
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
         
